baseURL = ""
languageCode = "en-us"
title = "Nathaniel's Blog"
theme = "hugo-kiera"

pygmentsCodeFences = true

#disqusShortname = "" #Disqus shortname
#googleAnalytics = "" #Google Analytics ID

[author]
    name = "Nathaniel Cantwell"           #Author name
    github = "natador"         #Github username
    gitlab = "natador"         #Gitlab username
    #twitter = "killbot4590"        #Twitter username
	linkedin = "ndcantwell"

[params]
    tagline = "Personal blog for Nathaniel Cantwell; opinions are mine"
    disableDarkModeCSS = true # disables css style for users using dark-mode
    mathJax = true
